apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data: 
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_USER: cG9zdGdyZXM=
---
apiVersion: v1
kind: PersistenVolumenClaim
metadatada:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13.1
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueForm:
                secretKeyref:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueForm:
                secretKeyref:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-storage
              mountPath: ../volumes/postgres
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None